Autolote/Autolote.WebAdmin/Controllers/MarcasController.cs
using Autolote.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Autolote.WebAdmin.Controllers
{
    [Authorize]
    public class MarcasController : Controller
    {
        MarcasBL _marcasBL;
        CategoriasBL _categoriasBL;


        public MarcasController()
        {
            _marcasBL = new MarcasBL();
            _categoriasBL = new CategoriasBL();
        }

        // GET: Marcas
        public ActionResult Index()
        {

            var listadeMarcas = _marcasBL.ObtenerProductos();
                        
            return View(listadeMarcas);
        }

        [HttpGet]
        public ActionResult Crear()
        {
            var NuevaMarca = new Productos();
            var categorias = _categoriasBL.ObtenerCategorias();

            ViewBag.CategoriaId = 
                new SelectList(categorias, "Id", "Descripcion");

            return View (NuevaMarca);
        }


        [HttpPost]
        public ActionResult Crear(Productos producto, HttpPostedFileBase imagen, HttpPostedFileBase imagen2, HttpPostedFileBase imagen3, HttpPostedFileBase imagen4, HttpPostedFileBase imagen5)
        {
            if (ModelState.IsValid)
            {
                if (producto.CategoriaId == 0)
                {
                    ModelState.AddModelError("CategoriaId", "Seleccione una categoria");
                    return View(producto);
                }
                Imagenes(producto, imagen, imagen2, imagen3, imagen4, imagen5);
                _marcasBL.GuardarProducto(producto);
                return RedirectToAction("Index");
            }
            var categorias = _categoriasBL.ObtenerCategorias();

            ViewBag.CategoriaId =
                new SelectList(categorias, "Id", "Descripcion");

            return View(producto);
            
        }

        public ActionResult Editar(int id)
        {
            var producto = _marcasBL.ObtenerProducto(id);
            var categorias = _categoriasBL.ObtenerCategorias();

            ViewBag.CategoriaId =
                new SelectList(categorias, "Id", "Descripcion", producto.CategoriaId);

            return View(producto);
        }

        [HttpPost]

        public ActionResult Editar(Productos producto, HttpPostedFileBase imagen, HttpPostedFileBase imagen2, HttpPostedFileBase imagen3, HttpPostedFileBase imagen4, HttpPostedFileBase imagen5)
        {
            if (ModelState.IsValid)
            {
                if (producto.CategoriaId == 0)
                {
                    ModelState.AddModelError("CategoriaId", "Seleccione una categoria");
                    return View(producto);
                }
                Imagenes(producto, imagen, imagen2, imagen3, imagen4, imagen5);

                _marcasBL.GuardarProducto(producto);


                return RedirectToAction("Index");
            }
            var categorias = _categoriasBL.ObtenerCategorias();

            ViewBag.CategoriaId =
                new SelectList(categorias, "Id", "Descripcion");

            return View(producto);
        }

        public ActionResult Detalle(int id)
        {
            var producto = _marcasBL.ObtenerProducto(id);

            return View(producto);
        }

        public ActionResult Eliminar(int id)
        {
            var producto = _marcasBL.ObtenerProducto(id);

            return View(producto);
        }

        [HttpPost]
        public ActionResult Eliminar(Productos producto)
        {
            _marcasBL.EliminarProducto(producto.Id);

            return RedirectToAction("Index");
        }

        private string GuardarImagen(HttpPostedFileBase imagen)
        {
            string path = Server.MapPath("~/Imagenes/" + imagen.FileName);
            imagen.SaveAs(path);

            return "/Imagenes/" + imagen.FileName;
        }

        public void Imagenes(Productos produc, HttpPostedFileBase i1, HttpPostedFileBase i2, HttpPostedFileBase i3, HttpPostedFileBase i4, HttpPostedFileBase i5)
        {
            if (i1 != null)
            {
                produc.UrlImagen = GuardarImagen(i1);
            }
            if (i2 != null)
            {
                produc.UrlImagen2 = GuardarImagen(i2);
            }
            if (i3 != null)
            {
                produc.UrlImagen3 = GuardarImagen(i3);
            }
            if (i4 != null)
            {
                produc.UrlImagen4 = GuardarImagen(i4);
            }
            if (i5 != null)
            {
                produc.UrlImagen5 = GuardarImagen(i5);
            }
        }
    }
}

Autolote/Autolote.WebAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Autolote Honduras</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Autolote", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <li>
                        @Html.ActionLink("Autos", "Index", "Marcas")
                    </li>
                    <li>
                        @Html.ActionLink("Categorias", "Index", "Categorias")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Autolote Honduras</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Autolote/Autolote.WebAdmin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap-clearmi.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/roboto.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/material-design.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/small-n-flat.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/custom.css">
    <title>@ViewBag.Title - Autolote Honduras</title>
</head>
<body class="cm-no-transition cm-1-navbar">
    <div id="cm-menu">
        <nav class="cm-navbar cm-navbar-primary">
            <div class="cm-flex">
                <a href="/" class="cm-logo">Auto<span>Lote</span></a>
            </div>
            <div class="btn btn-primary md-menu-white" data-toggle="cm-menu"></div>
        </nav>
        <div id="cm-menu-content">
            <div id="cm-menu-items-wrapper">
                <div id="cm-menu-scroller">
                    <ul class="cm-menu-items">
                        <li class="active"><a href="/" class="sf-house">Inicio</a></li>
                        <li class="active"><a href="/Categorias" class="sf-bell">Categorias</a></li>
                        <li class="active"><a href="/Marcas" class="sf-disc">Autos</a></li>
                    </ul>
                    
                </div>
            </div>
        </div>
    </div>
    <header id="cm-header">
        <nav class="cm-navbar cm-navbar-primary">
            <div class="btn btn-primary md-menu-white hidden-md hidden-lg" data-toggle="cm-menu"></div>
            <div class="cm-flex">
                <h1></h1>
                <form id="cm-search" action="index.html" method="get">
                    <input type="search" name="q" autocomplete="off" placeholder="Search...">
                </form>
            </div>
            <div class="dropdown pull-right">
                <button class="btn btn-primary md-account-circle-white" data-toggle="dropdown"></button>
                <ul class="dropdown-menu">
                    <li>
                        <a href="/Login"><i class="fa fa-fw fa-sign-out"></i> Salir</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div id="global">
        <div class="container-fluid">
            <div class="panel panel-default">
               
                <div class="panel-body" id="demo-buttons">
                    @RenderBody()
                </div>
            </div>
        </div>
        <footer class="cm-footer">
            <span class="pull-left">
                <p>&copy; @DateTime.Now.Year - Autolote Honduras</p>
            </span>
        </footer>
    </div>
    <script src="~/assets/js/lib/jquery-2.1.3.min.js"></script>
    <script src="~/assets/js/jquery.mousewheel.min.js"></script>
    <script src="~/assets/js/jquery.cookie.min.js"></script>
    <script src="~/assets/js/fastclick.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/clearmin.min.js"></script>
    <script src="~/assets/js/demo/home.js"></script>
</body>
</html>

Autolote/Autolote.WebAdmin/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap-clearmi.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/roboto.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/font-awesome.min.css">
    <title>@ViewBag.Title - Autolote Honduras</title>
    <style></style>
</head>
<body class="cm-login">
    <div class="text-center" style="padding:90px 0 30px 0;background:#fff;border-bottom:1px solid #ddd">
        <img src="~/assets/img/logo-big.svg" width="300" height="45">
    </div>

    <div class="col-sm-6 col-md-4 col-lg-3" style="margin:40px auto; float:none;">
        @RenderBody();
    </div>
</body>
</html>